export default {
  dataPath: [
    { text: 'data1', 'path': '../data1' },
    { text: 'data2', 'path': '../data2' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data3', 'path': '../data3' },
    { text: 'data4', 'path': '../data4' },
    { text: 'data5', 'path': '../data5' },
    { text: 'data6', 'path': '../data6' }
  ]
}
