/**
 * Created by liqiusheng on 17/7/5.
 */

// 获取当前页面的大小
export const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE'
export const UPDATE_PAGE_WIDTH = 'UPDATE_PAGE_WIDTH'
export const UPDATE_PAGE_HEIGHT = 'UPDATE_PAGE_HEIGHT'
export const EVENT_SUBMIT = 'EVENT_SUBMIT'
export const EXPORT_AREA = 'EXPORT_AREA'
// selection
export const CREATE_SELECTION = 'CREATE_SELECTION'
export const UPDATE_SELECTION = 'UPDATE_SELECTION'
export const ACTIVE_IMAGE_SELECTION = 'ACTIVE_IMAGE_SELECTION'
export const ACTIVE_REGION_SELECTION = 'ACTIVE_REGION_SELECTION'
export const IMAGE_TO_TAGGED_VIEW = 'IMAGE_TO_TAGGED_VIEW'
export const ADD_FEATURES = 'ADD_FEATURES'
export const IMG_COMPARE = 'IMG_COMPARE'
export const ACTIVE_REGION_SELECTION_IDS = 'ACTIVE_REGION_SELECTION_IDS'
export const ACTIVE_REGION_SELECTION_IMAGES = 'ACTIVE_REGION_SELECTION_IMAGES'
export const CHANGE_ICON_LIST = 'CHANGE_ICON_LIST'
export const TRANS_FEATURES = 'TRANS_FEATURES'
